Repository OCA/geospatial, pull requests merged in 2019-11, with the labels that each got.

#228 [12.0][ADD] base_google_map
  base_google_map/README.rst
  base_google_map/__init__.py
  base_google_map/__manifest__.py
  base_google_map/controllers/__init__.py
  base_google_map/controllers/main.py
  base_google_map/data/google_maps_libraries.xml
  base_google_map/i18n/web_google_maps.pot
  base_google_map/models/__init__.py
  base_google_map/models/res_config_settings.py
  base_google_map/readme/CONFIGURE.rst
  base_google_map/readme/CONTRIBUTORS.rst
  base_google_map/readme/DESCRIPTION.rst
  base_google_map/static/description/icon.png
  base_google_map/static/description/index.html
  base_google_map/static/description/thumbnails.png
  base_google_map/views/res_config_settings.xml
Labels: needs review

#223 [ADD][12.0] web_view_google_map
  web_view_google_map/README.rst
  web_view_google_map/__init__.py
  web_view_google_map/__manifest__.py
  web_view_google_map/hooks.py
  web_view_google_map/i18n/web_google_maps.pot
  web_view_google_map/models/__init__.py
  web_view_google_map/models/ir_act_window_view.py
  web_view_google_map/models/ir_ui_view.py
  web_view_google_map/readme/CONTRIBUTORS.rst
  web_view_google_map/readme/DESCRIPTION.rst
  web_view_google_map/readme/USAGE.rst
  web_view_google_map/static/description/icon.png
  web_view_google_map/static/description/index.html
  web_view_google_map/static/description/maps.png
  web_view_google_map/static/description/thumbnails.png
  web_view_google_map/static/description/widget_gplaces_address_form.gif
  web_view_google_map/static/description/widget_gplaces_autocomplete.gif
  web_view_google_map/static/lib/markercluster/img/m1.png
  web_view_google_map/static/lib/markercluster/img/m2.png
  web_view_google_map/static/lib/markercluster/img/m3.png
  web_view_google_map/static/lib/markercluster/img/m4.png
  web_view_google_map/static/lib/markercluster/img/m5.png
  web_view_google_map/static/lib/markercluster/markerclusterer.js
  web_view_google_map/static/src/img/layer_bike.png
  web_view_google_map/static/src/img/layer_traffic.png
  web_view_google_map/static/src/img/layer_transit.png
  web_view_google_map/static/src/img/markers/black.png
  web_view_google_map/static/src/img/markers/blue.png
  web_view_google_map/static/src/img/markers/brown.png
  web_view_google_map/static/src/img/markers/cyan.png
  web_view_google_map/static/src/img/markers/green.png
  web_view_google_map/static/src/img/markers/grey.png
  web_view_google_map/static/src/img/markers/light-green.png
  web_view_google_map/static/src/img/markers/magenta.png
  web_view_google_map/static/src/img/markers/orange.png
  web_view_google_map/static/src/img/markers/pink.png
  web_view_google_map/static/src/img/markers/purple.png
  web_view_google_map/static/src/img/markers/red.png
  web_view_google_map/static/src/img/markers/white.png
  web_view_google_map/static/src/img/markers/yellow.png
  web_view_google_map/static/src/img/mode_bicycling.png
  web_view_google_map/static/src/img/mode_driving.png
  web_view_google_map/static/src/img/mode_transit.png
  web_view_google_map/static/src/img/mode_walking.png
  web_view_google_map/static/src/js/fields/relational_fields.js
  web_view_google_map/static/src/js/view/map/map_controller.js
  web_view_google_map/static/src/js/view/map/map_model.js
  web_view_google_map/static/src/js/view/map/map_renderer.js
  web_view_google_map/static/src/js/view/map/map_view.js
  web_view_google_map/static/src/js/view/view_registry.js
  web_view_google_map/static/src/js/widgets/fields_registry.js
  web_view_google_map/static/src/js/widgets/gplaces_autocomplete.js
  web_view_google_map/static/src/js/widgets/utils.js
  web_view_google_map/static/src/scss/web_maps.scss
  web_view_google_map/static/src/scss/web_maps_mobile.scss
  web_view_google_map/static/src/xml/widget_places.xml
  web_view_google_map/views/google_places_template.xml
  web_view_google_map/views/res_partner.xml
Labels: approved, needs review

#229 [12.0][ADD] web_widget_google_marker_icon_picker
  web_widget_google_marker_icon_picker/README.rst
  web_widget_google_marker_icon_picker/__init__.py
  web_widget_google_marker_icon_picker/__manifest__.py
  web_widget_google_marker_icon_picker/readme/CONTRIBUTORS.rst
  web_widget_google_marker_icon_picker/readme/DESCRIPTION.rst
  web_widget_google_marker_icon_picker/readme/USAGE.rst
  web_widget_google_marker_icon_picker/static/description/icon.png
  web_widget_google_marker_icon_picker/static/description/index.html
  web_widget_google_marker_icon_picker/static/description/widget_marker_picker.png
  web_widget_google_marker_icon_picker/static/src/img/markers/aqua.png
  web_widget_google_marker_icon_picker/static/src/img/markers/blue-violet.png
  web_widget_google_marker_icon_picker/static/src/img/markers/blue.png
  web_widget_google_marker_icon_picker/static/src/img/markers/brown.png
  web_widget_google_marker_icon_picker/static/src/img/markers/deep-sky-blue.png
  web_widget_google_marker_icon_picker/static/src/img/markers/fuschia.png
  web_widget_google_marker_icon_picker/static/src/img/markers/gold.png
  web_widget_google_marker_icon_picker/static/src/img/markers/gray.png
  web_widget_google_marker_icon_picker/static/src/img/markers/green.png
  web_widget_google_marker_icon_picker/static/src/img/markers/indigo.png
  web_widget_google_marker_icon_picker/static/src/img/markers/lime-green.png
  web_widget_google_marker_icon_picker/static/src/img/markers/lime.png
  web_widget_google_marker_icon_picker/static/src/img/markers/maroon.png
  web_widget_google_marker_icon_picker/static/src/img/markers/navy.png
  web_widget_google_marker_icon_picker/static/src/img/markers/olive.png
  web_widget_google_marker_icon_picker/static/src/img/markers/orange.png
  web_widget_google_marker_icon_picker/static/src/img/markers/purple.png
  web_widget_google_marker_icon_picker/static/src/img/markers/red.png
  web_widget_google_marker_icon_picker/static/src/img/markers/teal.png
  web_widget_google_marker_icon_picker/static/src/img/markers/yellow.png
  web_widget_google_marker_icon_picker/static/src/js/view/map/map_renderer.js
  web_widget_google_marker_icon_picker/static/src/js/view/map/map_view.js
  web_widget_google_marker_icon_picker/static/src/js/widget/field_marker.js
  web_widget_google_marker_icon_picker/static/src/xml/marker_color.xml
  web_widget_google_marker_icon_picker/views/template.xml
Labels: approved, enhancement, needs review

#234 [IMP] base_google_maps: promote to App
  base_google_map/__manifest__.py
  base_google_map/readme/CONTRIBUTORS.rst
  base_google_map/readme/CREDITS.rst
  base_google_map/static/description/icon.png
  base_google_map/static/description/icon.svg
Labels: approved, enhancement, needs review
