Repository OCA/geospatial, pull requests merged in 2020-06, with the labels that each got.

#255 [MIG] geoengine_swisstopo: Migration to 13.0
  geoengine_swisstopo/__init__.py
  geoengine_swisstopo/__manifest__.py
  geoengine_swisstopo/geo_view/__init__.py
  geoengine_swisstopo/geo_view/geo_raster_layer.py
  geoengine_swisstopo/geo_view/geo_raster_layer_view.xml
  geoengine_swisstopo/i18n/geoengine_swisstopo.pot
  geoengine_swisstopo/readme/DESCRIPTION.rst
  geoengine_swisstopo/static/description/icon.png
  geoengine_swisstopo/static/src/js/.eslintrc
  geoengine_swisstopo/static/src/js/swisstopo_geoengine.js
  geoengine_swisstopo/views/geoengine_swisstopo_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#259 [12.0] [IMP] web_view_google_map: Lint Errors
  web_view_google_map/static/src/js/fields/relational_fields.js
  web_view_google_map/static/src/js/view/map/map_controller.js
  web_view_google_map/static/src/js/view/map/map_model.js
  web_view_google_map/static/src/js/view/map/map_renderer.js
  web_view_google_map/static/src/js/view/map/map_view.js
  web_view_google_map/static/src/js/widgets/fields_registry.js
  web_view_google_map/static/src/js/widgets/utils.js
Labels: approved, bot is merging ⏳

#257 [12.0] Fix default_extent in views
  base_geoengine/geo_model.py
  base_geoengine/static/src/js/widgets/geoengine_widgets.js
Labels: approved, needs fixing

#260 [FW] [13.0] Fix default_extent in views
  base_geoengine/geo_model.py
  base_geoengine/static/src/js/widgets/geoengine_widgets.js
Labels: bot is merging ⏳

#262 [10.0][FIX] demo data: unknown field 'symbol_binary' / fix travis
  .travis.yml
  base_geoengine/tests/test_geoengine.py
  base_geoengine_demo/models/retail_machine.py
  geoengine_partner/views/partner.xml
  geoengine_project/views/geo_project_view.xml
Labels: bot is merging ⏳

#261 [10.0][IMP] base_geoengine: allow custom configuration on layer opacity
  base_geoengine/static/src/js/views/geoengine_view.js
  base_geoengine/static/src/js/views/geoengine_widgets.js
  base_geoengine_demo/views/zip.xml
Labels: approved, bot is merging ⏳, ready to merge
