Repository OCA/geospatial, pull requests merged in 2023-01, with the labels that each got.

#319 [REF] use latest version of copier template (v1.14.0)
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
Labels: approved

#321 [12.0][FIX] base_geoengine. use shape() instead of asShape()
  base_geoengine/fields.py
  base_geoengine/geo_helper/geo_convertion_helper.py
Labels: approved, ready to merge

#325 [13.0][UPD] Move from travis to github actions
  .copier-answers.yml
  .flake8
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .travis.yml
  base_geoengine/fields.py
  base_geoengine/geo_db.py
  base_geoengine/geo_helper/geo_convertion_helper.py
  base_geoengine/geo_model.py
  base_geoengine/geo_operators.py
  base_geoengine/geo_view/geo_raster_layer.py
  base_geoengine/static/src/js/geoengine_common.js
  base_geoengine/static/src/js/views/form_renderer.js
  base_geoengine/static/src/js/views/geoengine/geoengine_controller.js
  base_geoengine/static/src/js/views/geoengine/geoengine_renderer.js
  base_geoengine/static/src/js/views/geoengine/geoengine_view.js
  base_geoengine/static/src/js/views/view_registry.js
  base_geoengine/static/src/js/widgets/geoengine_record.js
  base_geoengine/static/src/js/widgets/geoengine_template_widgets.js
  base_geoengine/static/src/js/widgets/geoengine_widgets.js
  geoengine_base_geolocalize/tests/test_geoengine_partner.py
  geoengine_swisstopo/static/src/js/swisstopo_geoengine.js
  requirements.txt
Labels: bot is merging ⏳

#322 [14.0][FIX] base_geoengine: use shape() instead of asShape()
  base_geoengine/geo_helper/geo_convertion_helper.py
Labels: bot is merging ⏳
