Repository OCA/geospatial, pull requests merged in 2024-10, with the labels that each got.

#372 [17.0][MIG] base_geoengine_demo: Migration to 17.0
  base_geoengine_demo/README.rst
  base_geoengine_demo/__init__.py
  base_geoengine_demo/__manifest__.py
  base_geoengine_demo/data/npa_geom.xml
  base_geoengine_demo/data/retail_machine_geom.xml
  base_geoengine_demo/i18n/base_geoengine_demo.pot
  base_geoengine_demo/i18n/es.po
  base_geoengine_demo/i18n/it.po
  base_geoengine_demo/images/map-hover.png
  base_geoengine_demo/images/map.png
  base_geoengine_demo/models/__init__.py
  base_geoengine_demo/models/geo_npa.py
  base_geoengine_demo/models/retail_machine.py
  base_geoengine_demo/pyproject.toml
  base_geoengine_demo/readme/CONTRIBUTORS.md
  base_geoengine_demo/readme/DESCRIPTION.md
  base_geoengine_demo/readme/INSTALL.md
  base_geoengine_demo/readme/USAGE.md
  base_geoengine_demo/security/ir.model.access.csv
  base_geoengine_demo/static/description/icon.png
  base_geoengine_demo/static/description/index.html
  base_geoengine_demo/views/menus.xml
  base_geoengine_demo/views/retail_machine.xml
  base_geoengine_demo/views/zip.xml
Labels: bot is merging ⏳

#380 [16][REF] split web_view_leaflet_map into web_view_leaflet_map and web_leaflet_lib
  setup/web_leaflet_lib/odoo/addons/web_leaflet_lib
  setup/web_leaflet_lib/setup.py
  web_leaflet_lib/README.rst
  web_leaflet_lib/__init__.py
  web_leaflet_lib/__manifest__.py
  web_leaflet_lib/data/ir_config_parameter.xml
  web_leaflet_lib/demo/ir_config_parameter.xml
  web_leaflet_lib/hooks.py
  web_leaflet_lib/i18n/fr.po
  web_leaflet_lib/models/__init__.py
  web_leaflet_lib/models/ir_http.py
  web_leaflet_lib/readme/CONFIGURE.rst
  web_leaflet_lib/readme/CONTRIBUTORS.rst
  web_leaflet_lib/readme/CREDITS.rst
  web_leaflet_lib/readme/DESCRIPTION.rst
  web_leaflet_lib/static/description/icon.png
  web_leaflet_lib/static/description/index.html
  web_leaflet_lib/static/lib/leaflet/images/layers-2x.png
  web_leaflet_lib/static/lib/leaflet/images/layers.png
  web_leaflet_lib/static/lib/leaflet/images/marker-icon-2x.png
  web_leaflet_lib/static/lib/leaflet/images/marker-icon.png
  web_leaflet_lib/static/lib/leaflet/images/marker-shadow.png
  web_leaflet_lib/static/lib/leaflet/leaflet.css
  web_leaflet_lib/static/lib/leaflet/leaflet.js
  web_leaflet_lib/static/lib/leaflet/leaflet.js.map
  web_view_leaflet_map/README.rst
  web_view_leaflet_map/__manifest__.py
  web_view_leaflet_map/i18n/fr.po
  web_view_leaflet_map/i18n/it.po
  web_view_leaflet_map/i18n/web_view_leaflet_map.pot
  web_view_leaflet_map/models/__init__.py
  web_view_leaflet_map/readme/CONFIGURE.rst
  web_view_leaflet_map/readme/DESCRIPTION.rst
  web_view_leaflet_map/static/description/index.html
Labels: approved, ready to merge, bot is merging ⏳

#382 [17.0][MIG] geoengine_base_geolocalize: Migration to 17.0
  geoengine_base_geolocalize/README.rst
  geoengine_base_geolocalize/__init__.py
  geoengine_base_geolocalize/__manifest__.py
  geoengine_base_geolocalize/i18n/geoengine_base_geolocalize.pot
  geoengine_base_geolocalize/i18n/it.po
  geoengine_base_geolocalize/models/__init__.py
  geoengine_base_geolocalize/models/res_partner.py
  geoengine_base_geolocalize/pyproject.toml
  geoengine_base_geolocalize/readme/CONTRIBUTORS.md
  geoengine_base_geolocalize/readme/DESCRIPTION.md
  geoengine_base_geolocalize/readme/INSTALL.md
  geoengine_base_geolocalize/static/description/icon.png
  geoengine_base_geolocalize/static/description/index.html
  geoengine_base_geolocalize/tests/__init__.py
  geoengine_base_geolocalize/tests/test_geoengine_partner.py
  geoengine_base_geolocalize/views/res_partner_view.xml
  requirements.txt
Labels: approved, bot is merging ⏳
